apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfcggdffgd-prod
  labels:
    environment-id: env_d4c213c1-32e8-4970-b740-093700320aba
    project-id: project_2b77845a-f59d-4624-b758-a63c7d6618e8
    project-name: dfgdfcggdffgd
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
